apiVersion: v1
kind: Secret
metadata:
  # This name will be use in injecteing this secrets in POD defination
  name: mysecret
type: Opaque
data:
  DB_Host: c3FsMDE=
  DB_User: cm9vdA==
  DB_Password: cGFzc3dvcmQxMjM=
# echo -n 'password123' | base64
